language: node_js
node_js:
  - "stable"

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: Kikobeats/react-boilerplatinum
    - GIT_SOURCE: src/www
    - GIT_BRANCH: gh-pages

after_script:
  - |
      declare exitCode;
      # -- [1] -------------------------------------------------------
      $(npm bin)/travis-after-all
      exitCode=$?
      # -- [2] -------------------------------------------------------
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $exitCode -eq 0 ]; then
        npm install git-update-ghpages
        npm run build && ./node_modules/.bin/git-update-ghpages -e
      fi
